twitter:
  callback: http://54.250.153.228/oauth/callback?provider=twitter
aws:
  access_key: <%= Rails.application.credentials.aws[:access_key] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  s3_bucket: <%= Rails.application.credentials.aws[:s3_bucket] %>